# Avances
## Grupo 2

##### Importación de librerías.

In [1]:
import pandas as pd

##### Importación de datos

In [2]:
df = pd.read_csv('DATOS_CRUDOS.csv')
df.head()

,CODIGO,DISTRITO,DEPARTAMENTO,MUNICIPIO,ESTABLECIMIENTO,DIRECCION,TELEFONO,SUPERVISOR,DIRECTOR,NIVEL,SECTOR,AREA,STATUS,MODALIDAD,JORNADA,PLAN,DEPARTAMENTAL
0,16-01-0137-46,16-006,ALTA VERAPAZ,COBAN,INSTITUTO MIXTO NOCTURNO FRANCISCO MARROQUIN,6A. AVENIDA 1-15 ZONA 4,NaN,JORGE EDUARDO PAQUE LAZARO,--,DIVERSIFICADO,PRIVADO,URBANA,CERRADA DEFINITIVAMENTE,MONOLINGUE,NOCTURNA,DIARIO(REGULAR),ALTA VERAPAZ
1,16-01-0138-46,16-01-0926,ALTA VERAPAZ,COBAN,COLEGIO COBAN,KM.2 SALIDA A SAN JUAN CHAMELCO ZONA 8,77945104,JOSE ARTURO CHOC CHEN,GUSTAVO ADOLFO SIERRA POP,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
2,16-01-0139-46,16-01-0927,ALTA VERAPAZ,COBAN,COLEGIO PARTICULAR MIXTO VERAPAZ,KM 209.5 ENTRADA A LA CIUDAD,58015763,ARMANDO AUDILIO POP CUCUL,GILMA DOLORES GUAY PAZ DE LEAL,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
3,16-01-0140-46,16-01-0926,ALTA VERAPAZ,COBAN,"COLEGIO ""LA INMACULADA""",7A. AVENIDA 11-109 ZONA 6,78232301,JOSE ARTURO CHOC CHEN,VIRGINIA SOLANO SERRANO,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
4,16-01-0141-46,16-01-0924,ALTA VERAPAZ,COBAN,ESCUELA NACIONAL DE CIENCIAS COMERCIALES,2A CALLE 11-10 ZONA 2,40389968,MOISÉS ADRIÁN LÓPEZ PÉREZ,ESTELA DEL CARMEN QUIM ROSALES,DIVERSIFICADO,OFICIAL,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ

### A. Número de registros y variables.

In [3]:
n_registros, n_variables = df.shape
print('La cantidad de registros es: ', n_registros)
print('La cantidad de variables es: ', n_variables)

La cantidad de registros es:  9728
La cantidad de variables es:  17

### B. Tipo de dato de cada variable.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9728 entries, 0 to 9727
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CODIGO           9706 non-null   object
 1   DISTRITO         9405 non-null   object
 2   DEPARTAMENTO     9706 non-null   object
 3   MUNICIPIO        9706 non-null   object
 4   ESTABLECIMIENTO  9703 non-null   object
 5   DIRECCION        9637 non-null   object
 6   TELEFONO         9024 non-null   object
 7   SUPERVISOR       9402 non-null   object
 8   DIRECTOR         8510 non-null   object
 9   NIVEL            9706 non-null   object
 10  SECTOR           9706 non-null   object
 11  AREA             9706 non-null   object
 12  STATUS           9706 non-null   object
 13  MODALIDAD        9706 non-null   object
 14  JORNADA          9706 non-null   object
 15  PLAN             9706 non-null   object
 16  DEPARTAMENTAL    9706 non-null   object
dtypes: object(17)
memory usage: 1.3+ MB

Todas las variables son categóricas.

### C. Cantidad y porcentaje de valores faltantes por variable.

In [5]:
faltantes = {'Cantidad': [],
             'Porcentaje %': []}

for x in df.columns:
    cantidad = int(df[x].isna().sum())
    porcentaje = cantidad*100/n_registros

    faltantes['Cantidad'].append(cantidad)
    faltantes['Porcentaje %'].append(porcentaje)

faltantes_df = pd.DataFrame(faltantes, index= df.columns)
faltantes_df

                 Cantidad  Porcentaje %
CODIGO                 22      0.226151
DISTRITO              323      3.320312
DEPARTAMENTO           22      0.226151
MUNICIPIO              22      0.226151
ESTABLECIMIENTO        25      0.256990
DIRECCION              91      0.935444
TELEFONO              704      7.236842
SUPERVISOR            326      3.351151
DIRECTOR             1218     12.520559
NIVEL                  22      0.226151
SECTOR                 22      0.226151
AREA                   22      0.226151
STATUS                 22      0.226151
MODALIDAD              22      0.226151
JORNADA                22      0.226151
PLAN                   22      0.226151
DEPARTAMENTAL          22      0.226151

### D. Cantidad de valores únicos.

In [6]:
unicos = {'Cantidad': []}

for x in df.columns:
    cantidad = int(df[x].nunique())
    unicos['Cantidad'].append(cantidad)

unicos_df = pd.DataFrame(unicos, index= df.columns)
unicos_df

                 Cantidad
CODIGO               9706
DISTRITO             1594
DEPARTAMENTO           22
MUNICIPIO             330
ESTABLECIMIENTO      5036
DIRECCION            6023
TELEFONO             5546
SUPERVISOR           1243
DIRECTOR             4854
NIVEL                   1
SECTOR                  4
AREA                    3
STATUS                  5
MODALIDAD               2
JORNADA                 6
PLAN                   13
DEPARTAMENTAL          26

### E. Cantidad de registros duplicados exactos.

In [7]:
print('Hay en total:', df.duplicated().sum(), 'datos duplicados.')

Hay en total: 21 datos duplicados.

### F. Variables con valores fuera de dominio o inconsistentes.

In [8]:
df['DEPARTAMENTO'].unique()

array(['ALTA VERAPAZ', nan, 'BAJA VERAPAZ', 'CHIMALTENANGO', 'CHIQUIMULA',
       'EL PROGRESO', 'ESCUINTLA', 'GUATEMALA', 'HUEHUETENANGO', 'IZABAL',
       'JALAPA', 'JUTIAPA', 'PETEN', 'QUETZALTENANGO', 'QUICHE',
       'RETALHULEU', 'SACATEPEQUEZ', 'SAN MARCOS', 'SANTA ROSA', 'SOLOLA',
       'SUCHITEPEQUEZ', 'TOTONICAPAN', 'ZACAPA'], dtype=object)

In [9]:
df['NIVEL'].unique()

array(['DIVERSIFICADO', nan], dtype=object)

In [10]:
df['SECTOR'].unique()

array(['PRIVADO', 'OFICIAL', 'MUNICIPAL', 'COOPERATIVA', nan],
      dtype=object)

In [11]:
df['AREA'].unique()

array(['URBANA', 'RURAL', 'SIN ESPECIFICAR', nan], dtype=object)

In [12]:
df['STATUS'].unique()

array(['CERRADA DEFINITIVAMENTE', 'ABIERTA', 'CERRADA TEMPORALMENTE',
       'TEMPORAL NOMBRAMIENTO', nan, 'TEMPORAL TITULOS'], dtype=object)

In [13]:
df['MODALIDAD'].unique()

array(['MONOLINGUE', 'BILINGUE', nan], dtype=object)

In [14]:
df['JORNADA'].unique()

array(['NOCTURNA', 'MATUTINA', 'VESPERTINA', 'DOBLE', 'SIN JORNADA', nan,
       'INTERMEDIA'], dtype=object)

In [15]:
df['PLAN'].unique()

array(['DIARIO(REGULAR)', 'FIN DE SEMANA', 'A DISTANCIA',
       'SEMIPRESENCIAL', 'VIRTUAL A DISTANCIA',
       'SEMIPRESENCIAL (FIN DE SEMANA)',
       'SEMIPRESENCIAL (UN DÍA A LA SEMANA)', 'SABATINO', nan,
       'SEMIPRESENCIAL (DOS DÍAS A LA SEMANA)', 'DOMINICAL', 'MIXTO',
       'INTERCALADO', 'IRREGULAR'], dtype=object)

In [16]:
df['DEPARTAMENTAL'].unique()

array(['ALTA VERAPAZ', nan, 'BAJA VERAPAZ', 'CHIMALTENANGO', 'CHIQUIMULA',
       'EL PROGRESO', 'ESCUINTLA', 'GUATEMALA NORTE', 'GUATEMALA ORIENTE',
       'GUATEMALA OCCIDENTE', 'GUATEMALA SUR', 'HUEHUETENANGO', 'IZABAL',
       'JALAPA', 'JUTIAPA', 'PETÉN', 'QUETZALTENANGO', 'QUICHÉ',
       'QUICHÉ NORTE', 'RETALHULEU', 'SACATEPÉQUEZ', 'SAN MARCOS',
       'SANTA ROSA', 'SOLOLÁ', 'SUCHITEPÉQUEZ', 'TOTONICAPÁN', 'ZACAPA'],
      dtype=object)

In [17]:
pd.Series([len(str(x)) for x in df['TELEFONO']]).unique()

array([ 3,  8,  7, 17,  6, 26,  4, 11,  9, 16,  5, 15, 18,  2, 13])

- Departamental es una variable que divide el departamento de Guatemala en 4 regiones y a Quiché en 2.
- Hay números de teléfono con muchos dígitos (puede que sean varios números) y hay otros con pocos dígitos (menos de 8), los cuales puede que no estén bien escritos.

### G. Variables con formatos inconsistentes.

In [18]:
pd.Series([len(str(x)) for x in df['CODIGO']]).unique()

array([13,  3])

In [19]:
pd.Series([len(str(x)) for x in df['DISTRITO']]).unique()

array([ 6, 10,  3])

In [24]:
df['DISTRITO'].unique()

array(['16-006', '16-01-0926', '16-01-0927', ..., '19-021', '19-10-1140',
       '19-11-1141'], shape=(1595,), dtype=object)

In [20]:
df['MUNICIPIO'].unique()

array(['COBAN', 'SANTA CRUZ VERAPAZ', 'SAN CRISTOBAL VERAPAZ', 'TACTIC',
       'TAMAHU', 'SAN MIGUEL TUCURU', 'PANZOS', 'SENAHU',
       'SAN PEDRO CARCHA', 'SAN JUAN CHAMELCO', 'LANQUIN',
       'SANTA MARIA CAHABON', 'CHISEC', 'CHAHAL',
       'FRAY BARTOLOME DE LAS CASAS', 'LA TINTA', 'RAXRUHA', nan,
       'SALAMA', 'SAN MIGUEL CHICAJ', 'RABINAL', 'CUBULCO', 'GRANADOS',
       'SANTA CRUZ EL CHOL', 'SAN JERONIMO', 'PURULHA', 'CHIMALTENANGO',
       'SAN JOSE POAQUIL', 'SAN MARTIN JILOTEPEQUE', 'SAN JUAN COMALAPA',
       'SANTA APOLONIA', 'TECPAN GUATEMALA', 'PATZUN',
       'SAN MIGUEL POCHUTA', 'PATZICIA', 'SANTA CRUZ BALANYA',
       'ACATENANGO', 'SAN PEDRO YEPOCAPA', 'SAN ANDRES ITZAPA',
       'PARRAMOS', 'ZARAGOZA', 'EL TEJAR', 'CHIQUIMULA',
       'SAN JOSE LA ARADA', 'SAN JUAN ERMITA', 'JOCOTAN', 'CAMOTAN',
       'OLOPA', 'ESQUIPULAS', 'CONCEPCION LAS MINAS', 'QUEZALTEPEQUE',
       'SAN JACINTO', 'IPALA', 'GUASTATOYA', 'MORAZAN',
       'SAN AGUSTIN ACASAGUASTLAN', 'SAN CRISTOBAL ACASAGUASTLAN',
       'EL JICARO', 'SANSARE', 'SANARATE', 'SAN ANTONIO LA PAZ',
       'ESCUINTLA', 'SANTA LUCIA COTZUMALGUAPA', 'LA DEMOCRACIA',
       'SIQUINALA', 'MASAGUA', 'TIQUISATE', 'LA GOMERA', 'GUANAGAZAPA',
       'SAN JOSE', 'IZTAPA', 'PALIN', 'SAN VICENTE PACAYA',
       'NUEVA CONCEPCION', 'SIPACATE', 'GUATEMALA',
       'SANTA CATARINA PINULA', 'SAN JOSE PINULA', 'SAN JOSE DEL GOLFO',
       'PALENCIA', 'CHINAUTLA', 'SAN PEDRO AYAMPUC', 'MIXCO',
       'SAN PEDRO SACATEPEQUEZ', 'SAN JUAN SACATEPEQUEZ', 'SAN RAYMUNDO',
       'CHUARRANCHO', 'FRAIJANES', 'AMATITLAN', 'VILLA NUEVA',
       'VILLA CANALES', 'SAN MIGUEL PETAPA', 'HUEHUETENANGO', 'CHIANTLA',
       'MALACATANCITO', 'CUILCO', 'NENTON', 'SAN PEDRO NECTA',
       'JACALTENANGO', 'SAN PEDRO SOLOMA', 'SAN ILDEFONSO IXTAHUACAN',
       'SANTA BARBARA', 'LA LIBERTAD', 'SAN MIGUEL ACATAN',
       'SAN RAFAEL LA INDEPENDENCIA', 'TODOS SANTOS CUCHUMATAN',
       'SAN JUAN ATITAN', 'SANTA EULALIA', 'SAN MATEO IXTATAN',
       'COLOTENANGO', 'SAN SEBASTIAN HUEHUETENANGO', 'TECTITAN',
       'CONCEPCION HUISTA', 'SAN JUAN IXCOY', 'SAN ANTONIO HUISTA',
       'SAN SEBASTIAN COATAN', 'SANTA CRUZ BARILLAS', 'AGUACATAN',
       'SAN RAFAEL PETZAL', 'SAN GASPAR IXCHIL', 'SANTIAGO CHIMALTENANGO',
       'SANTA ANA HUISTA', 'UNION CANTINIL', 'PETATAN', 'PUERTO BARRIOS',
       'LIVINGSTON', 'EL ESTOR', 'MORALES', 'LOS AMATES', 'JALAPA',
       'SAN PEDRO PINULA', 'SAN LUIS JILOTEPEQUE', 'SAN MANUEL CHAPARRON',
       'SAN CARLOS ALZATATE', 'MONJAS', 'MATAQUESCUINTLA', 'JUTIAPA',
       'EL PROGRESO', 'SANTA CATARINA MITA', 'AGUA BLANCA',
       'ASUNCION MITA', 'YUPILTEPEQUE', 'ATESCATEMPA', 'JEREZ',
       'EL ADELANTO', 'ZAPOTITLAN', 'COMAPA', 'JALPATAGUA', 'CONGUACO',
       'MOYUTA', 'PASACO', 'SAN JOSE ACATEMPA', 'QUESADA', 'FLORES',
       'SAN BENITO', 'SAN ANDRES', 'SAN FRANCISCO', 'SANTA ANA',
       'DOLORES', 'SAN LUIS', 'SAYAXCHE', 'MELCHOR DE MENCOS', 'POPTUN',
       'LAS CRUCES', 'EL CHAL', 'QUETZALTENANGO', 'SALCAJA',
       'OLINTEPEQUE', 'SAN CARLOS SIJA', 'SIBILIA', 'CABRICAN', 'CAJOLA',
       'SAN MIGUEL SIGUILA', 'SAN JUAN OSTUNCALCO', 'SAN MATEO',
       'CONCEPCION CHIQUIRICHAPA', 'SAN MARTIN SACATEPEQUEZ', 'ALMOLONGA',
       'CANTEL', 'HUITAN', 'ZUNIL', 'COLOMBA COSTA CUCA',
       'SAN FRANCISCO LA UNION', 'EL PALMAR', 'COATEPEQUE',
       'GENOVA COSTA CUCA', 'FLORES COSTA CUCA', 'LA ESPERANZA',
       'PALESTINA DE LOS ALTOS', 'SANTA CRUZ DEL QUICHE', 'CHICHE',
       'CHINIQUE', 'ZACUALPA', 'CHAJUL', 'SANTO TOMAS CHICHICASTENANGO',
       'PATZITE', 'SAN ANTONIO ILOTENANGO', 'SAN PEDRO JOCOPILAS',
       'CUNEN', 'SAN JUAN COTZAL', 'JOYABAJ', 'NEBAJ',
       'SAN ANDRES SAJCABAJA', 'SAN MIGUEL USPANTAN', 'SACAPULAS',
       'SAN BARTOLOME JOCOTENANGO', 'CANILLA', 'CHICAMAN', 'IXCAN',
       'PACHALUN', 'RETALHULEU', 'SAN SEBASTIAN', 'SANTA CRUZ MULUA',
       'SAN MARTIN ZAPOTITLAN', 'SAN FELIPE', 'SAN ANDRES VILLA SECA',
       'CHAMPERICO', 'NUEVO SAN CARLOS', 'EL ASINTAL',
       'ANTIGUA GUATEMALA', 'JOCOTENANGO', 'PASTORES', 'SUMPANGO',
       'SANTO DOMINGO XENACOJ', 'SANTIAGO SACATEPEQUEZ',
       'SAN BARTOLOME MILPAS ALTAS', 'SAN LUCAS SACATEPEQUEZ',
       'SANTA LUCIA MILPAS ALTAS', 'MAGDALENA MILPAS ALTAS',
       'SANTA MARIA DE JESUS', 'CIUDAD VIEJA', 'SAN MIGUEL DUENAS',
       'ALOTENANGO', 'SAN ANTONIO AGUAS CALIENTES',
       'SANTA CATARINA BARAHONA', 'SAN MARCOS',
       'SAN ANTONIO SACATEPEQUEZ', 'COMITANCILLO',
       'SAN MIGUEL IXTAHUACAN', 'CONCEPCION TUTUAPA', 'TACANA', 'SIBINAL',
       'TAJUMULCO', 'TEJUTLA', 'SAN RAFAEL PIE DE LA CUESTA',
       'NUEVO PROGRESO', 'EL TUMBADOR', 'SAN JOSE EL RODEO', 'MALACATAN',
       'CATARINA', 'AYUTLA', 'OCOS', 'SAN PABLO', 'EL QUETZAL',
       'LA REFORMA', 'PAJAPITA', 'IXCHIGUAN', 'SAN JOSE OJETENAM',
       'SAN CRISTOBAL CUCHO', 'SIPACAPA', 'ESQUIPULAS PALO GORDO',
       'RIO BLANCO', 'SAN LORENZO', 'LA BLANCA', 'CUILAPA', 'BARBERENA',
       'SANTA ROSA DE LIMA', 'CASILLAS', 'SAN RAFAEL LAS FLORES',
       'ORATORIO', 'SAN JUAN TECUACO', 'CHIQUIMULILLA', 'TAXISCO',
       'SANTA MARIA IXHUATAN', 'GUAZACAPAN', 'SANTA CRUZ NARANJO',
       'PUEBLO NUEVO VIÑAS', 'NUEVA SANTA ROSA', 'SOLOLA',
       'SAN JOSE CHACAYA', 'SANTA MARIA VISITACION',
       'SANTA LUCIA UTATLAN', 'NAHUALA', 'SANTA CATARINA IXTAHUACAN',
       'SANTA CLARA LA LAGUNA', 'SAN ANDRES SEMETABAJ', 'PANAJACHEL',
       'SAN ANTONIO PALOPO', 'SAN LUCAS TOLIMAN', 'SAN PABLO LA LAGUNA',
       'SAN MARCOS LA LAGUNA', 'SAN JUAN LA LAGUNA',
       'SAN PEDRO LA LAGUNA', 'SANTIAGO ATITLAN', 'MAZATENANGO',
       'CUYOTENANGO', 'SAN FRANCISCO ZAPOTITLAN', 'SAN BERNARDINO',
       'SAN JOSE EL IDOLO', 'SANTO DOMINGO SUCHITEPEQUEZ', 'SAMAYAC',
       'SAN PABLO JOCOPILAS', 'SAN ANTONIO SUCHITEPEQUEZ',
       'SAN MIGUEL PANAM', 'SAN GABRIEL', 'CHICACAO', 'PATULUL',
       'SANTO TOMAS LA UNION', 'ZUNILITO', 'PUEBLO NUEVO', 'RIO BRAVO',
       'SAN JOSE LA MAQUINA', 'TOTONICAPAN', 'SAN CRISTOBAL TOTONICAPAN',
       'SAN FRANCISCO EL ALTO', 'SAN ANDRES XECUL', 'MOMOSTENANGO',
       'SANTA MARIA CHIQUIMULA', 'SANTA LUCIA LA REFORMA',
       'SAN BARTOLO AGUAS CALIENTES', 'ZACAPA', 'ESTANZUELA', 'RIO HONDO',
       'GUALAN', 'TECULUTAN', 'USUMATLAN', 'CABAÑAS', 'SAN DIEGO',
       'LA UNION', 'HUITE', 'SAN JORGE'], dtype=object)

In [21]:
pd.Series([len(str(x)) for x in df['ESTABLECIMIENTO']]).unique()

array([ 44,  13,  32,  23,  40,  55,  33,  47,  48,  22,  45,  30,  25,
        21, 105,  87,  39,  27,  36,  59,  24,  94,  46,  42,  51,   3,
        19,  37,  28,  49,  31,  35,  26,  18,  50,  63,  38,  62,  53,
        54,  34,  29,  16,  80,  65,  15,  17,  66,  78,  76,  52,  58,
        73,  64,  43,  71,  57,  68,  60,  41,  81,  61,  70,  77,  79,
       109,  91,  82,  14,  92,  97,  74, 104, 118,  83,  67, 101,  56,
       112,  75,  86,  84,   4,  95, 103,  90,  72,  88,  12,  20,  93,
        69, 100,  96,  99, 125, 121, 122,  89,  11,  85, 107, 113, 123,
        98, 116,   5, 114,   6, 128])

In [22]:
pd.Series([len(str(x)) for x in df['DIRECTOR']]).unique()

array([ 2, 25, 30, 23, 27, 26, 18, 34, 22, 24, 29, 19, 28, 20, 32, 21, 35,
        3, 31, 17, 38, 16, 36, 33, 15,  8,  1,  7, 14, 13, 37, 55, 41, 43,
       42, 52, 40,  4, 39,  6,  5, 47, 11, 45, 51, 50, 10, 49, 12, 44])

- Los códigos tienen 2 distintas longitudes.
- Los distritos son código pero tienen distintas longitudes también.
- Hay establecimientos con longitudes de 5 o menos, por lo que pueden haber errores o falta de información.
- Hay directores que tienen una cantidad pequeña de caractéres y otros que tienen muchos, se trendrán que evaluar.

### I. Identificación de problemas potenciales de calidad de datos.

- Todas las columnas tienen valores nulos.
- Hay columnas en las que los datos tienen longitudes menores o mayores a las esperadas, pudiendo reflejar falta de información o que se tiene más datos que un solo elemento.
- La columna departamental agrega poca información, ya que solo divide a dos departamentos.

### Plan de limpieza.

##### CODIGO

##### DISTRITO

##### DEPARTAMENTO

##### MUNICIPIO

##### ESTABLECIMIENTO

##### DIRECCION

##### TELEFONO

##### SUPERVISOR

##### DIRECTOR

##### NIVEL

##### SECTOR

##### AREA

##### STATUS

##### MODALIDAD

##### JORNADA

##### PLAN

##### DEPARTAMENTAL