In [2]:
import pandas as pd
import numpy as np

In [3]:
filename= 'DATOS_CRUDOS.csv'
data= pd.read_csv(filename, index_col=0)
df=pd.DataFrame(data)
df.head()

,DISTRITO,DEPARTAMENTO,MUNICIPIO,ESTABLECIMIENTO,DIRECCION,TELEFONO,SUPERVISOR,DIRECTOR,NIVEL,SECTOR,AREA,STATUS,MODALIDAD,JORNADA,PLAN,DEPARTAMENTAL
CODIGO,,,,,,,,,,,,,,,,
16-01-0137-46,16-006,ALTA VERAPAZ,COBAN,INSTITUTO MIXTO NOCTURNO FRANCISCO MARROQUIN,6A. AVENIDA 1-15 ZONA 4,NaN,JORGE EDUARDO PAQUE LAZARO,--,DIVERSIFICADO,PRIVADO,URBANA,CERRADA DEFINITIVAMENTE,MONOLINGUE,NOCTURNA,DIARIO(REGULAR),ALTA VERAPAZ
16-01-0138-46,16-01-0926,ALTA VERAPAZ,COBAN,COLEGIO COBAN,KM.2 SALIDA A SAN JUAN CHAMELCO ZONA 8,77945104,JOSE ARTURO CHOC CHEN,GUSTAVO ADOLFO SIERRA POP,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
16-01-0139-46,16-01-0927,ALTA VERAPAZ,COBAN,COLEGIO PARTICULAR MIXTO VERAPAZ,KM 209.5 ENTRADA A LA CIUDAD,58015763,ARMANDO AUDILIO POP CUCUL,GILMA DOLORES GUAY PAZ DE LEAL,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
16-01-0140-46,16-01-0926,ALTA VERAPAZ,COBAN,"COLEGIO ""LA INMACULADA""",7A. AVENIDA 11-109 ZONA 6,78232301,JOSE ARTURO CHOC CHEN,VIRGINIA SOLANO SERRANO,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
16-01-0141-46,16-01-0924,ALTA VERAPAZ,COBAN,ESCUELA NACIONAL DE CIENCIAS COMERCIALES,2A CALLE 11-10 ZONA 2,40389968,MOISÉS ADRIÁN LÓPEZ PÉREZ,ESTELA DEL CARMEN QUIM ROSALES,DIVERSIFICADO,OFICIAL,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ

Análsis de las variables

In [4]:
df.info()

<class 'pandas.DataFrame'>
Index: 9728 entries, 16-01-0137-46 to nan
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DISTRITO         9405 non-null   str
 1   DEPARTAMENTO     9706 non-null   str
 2   MUNICIPIO        9706 non-null   str
 3   ESTABLECIMIENTO  9703 non-null   str
 4   DIRECCION        9637 non-null   str
 5   TELEFONO         9024 non-null   str
 6   SUPERVISOR       9402 non-null   str
 7   DIRECTOR         8510 non-null   str
 8   NIVEL            9706 non-null   str
 9   SECTOR           9706 non-null   str
 10  AREA             9706 non-null   str
 11  STATUS           9706 non-null   str
 12  MODALIDAD        9706 non-null   str
 13  JORNADA          9706 non-null   str
 14  PLAN             9706 non-null   str
 15  DEPARTAMENTAL    9706 non-null   str
dtypes: str(16)
memory usage: 1.3+ MB

Se observa que todas las variables son cadenas. Son aproximadamente 16 variables. No todas son indispensables, por lo que se proccederá al su correspondiente eliminación del conjunto.

In [5]:
df=df.drop(columns= ['DISTRITO', 'TELEFONO', 'DIRECCION'])
df

,DEPARTAMENTO,MUNICIPIO,ESTABLECIMIENTO,SUPERVISOR,DIRECTOR,NIVEL,SECTOR,AREA,STATUS,MODALIDAD,JORNADA,PLAN,DEPARTAMENTAL
CODIGO,,,,,,,,,,,,,
16-01-0137-46,ALTA VERAPAZ,COBAN,INSTITUTO MIXTO NOCTURNO FRANCISCO MARROQUIN,JORGE EDUARDO PAQUE LAZARO,--,DIVERSIFICADO,PRIVADO,URBANA,CERRADA DEFINITIVAMENTE,MONOLINGUE,NOCTURNA,DIARIO(REGULAR),ALTA VERAPAZ
16-01-0138-46,ALTA VERAPAZ,COBAN,COLEGIO COBAN,JOSE ARTURO CHOC CHEN,GUSTAVO ADOLFO SIERRA POP,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
16-01-0139-46,ALTA VERAPAZ,COBAN,COLEGIO PARTICULAR MIXTO VERAPAZ,ARMANDO AUDILIO POP CUCUL,GILMA DOLORES GUAY PAZ DE LEAL,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
16-01-0140-46,ALTA VERAPAZ,COBAN,"COLEGIO ""LA INMACULADA""",JOSE ARTURO CHOC CHEN,VIRGINIA SOLANO SERRANO,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
16-01-0141-46,ALTA VERAPAZ,COBAN,ESCUELA NACIONAL DE CIENCIAS COMERCIALES,MOISÉS ADRIÁN LÓPEZ PÉREZ,ESTELA DEL CARMEN QUIM ROSALES,DIVERSIFICADO,OFICIAL,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19-10-0013-46,ZACAPA,HUITE,INSTITUTO DIVERSIFICADO,SILDY MARIELA PÉREZ FRANCO,WUENDY JHOJANA SIERRA PAZ,DIVERSIFICADO,OFICIAL,URBANA,ABIERTA,MONOLINGUE,NOCTURNA,DIARIO(REGULAR),ZACAPA
19-10-1009-46,ZACAPA,HUITE,INSTITUTO DIVERSIFICADO POR COOPERATIVA,SILDY MARIELA PÉREZ FRANCO,ROBIDIO PORTILLO SALGUERO,DIVERSIFICADO,COOPERATIVA,URBANA,ABIERTA,MONOLINGUE,VESPERTINA,DIARIO(REGULAR),ZACAPA
19-11-0018-46,ZACAPA,SAN JORGE,INSTITUTO MIXTO DE EDUCACIÓN DIVERSIFICADA POR...,ALBA LUZ MÉNDEZ,VICTOR HUGO GUERRA MONROY,DIVERSIFICADO,COOPERATIVA,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ZACAPA
19-11-0029-46,ZACAPA,SAN JORGE,INED INSTITUTO NACIONAL DE EDUCACIÓN DIVERSIFI...,ALBA LUZ MÉNDEZ,NaN,DIVERSIFICADO,OFICIAL,URBANA,ABIERTA,MONOLINGUE,VESPERTINA,DIARIO(REGULAR),ZACAPA
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df.shape

(9728, 13)

Conteo de valores nulos por variable

In [16]:
# Count missing values in the DataFrame
missing_values = df.isnull().sum()
print(missing_values)

DEPARTAMENTO         22
MUNICIPIO            22
ESTABLECIMIENTO      25
SUPERVISOR          326
DIRECTOR           1218
NIVEL                22
SECTOR               22
AREA                 22
STATUS               22
MODALIDAD            22
JORNADA              22
PLAN                 22
DEPARTAMENTAL        22
dtype: int64

In [23]:
di=pd.DataFrame(missing_values)
print("Valores NaN: ",di.sum())
print("Proporción de NaN respecto al total: ", di.sum()/ 9728)
print("Porcentaje de NaN respecto al total: ", (di.sum()/ 9728)*100)

Valores NaN:  0    1789
dtype: int64
Proporción de NaN respecto al total:  0    0.183902
dtype: float64
Porcentaje de NaN respecto al total:  0    18.390214
dtype: float64

In [24]:
df=df.dropna()#eliminación de datos nulos NaN
df

,DEPARTAMENTO,MUNICIPIO,ESTABLECIMIENTO,SUPERVISOR,DIRECTOR,NIVEL,SECTOR,AREA,STATUS,MODALIDAD,JORNADA,PLAN,DEPARTAMENTAL
CODIGO,,,,,,,,,,,,,
16-01-0137-46,ALTA VERAPAZ,COBAN,INSTITUTO MIXTO NOCTURNO FRANCISCO MARROQUIN,JORGE EDUARDO PAQUE LAZARO,--,DIVERSIFICADO,PRIVADO,URBANA,CERRADA DEFINITIVAMENTE,MONOLINGUE,NOCTURNA,DIARIO(REGULAR),ALTA VERAPAZ
16-01-0138-46,ALTA VERAPAZ,COBAN,COLEGIO COBAN,JOSE ARTURO CHOC CHEN,GUSTAVO ADOLFO SIERRA POP,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
16-01-0139-46,ALTA VERAPAZ,COBAN,COLEGIO PARTICULAR MIXTO VERAPAZ,ARMANDO AUDILIO POP CUCUL,GILMA DOLORES GUAY PAZ DE LEAL,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
16-01-0140-46,ALTA VERAPAZ,COBAN,"COLEGIO ""LA INMACULADA""",JOSE ARTURO CHOC CHEN,VIRGINIA SOLANO SERRANO,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
16-01-0141-46,ALTA VERAPAZ,COBAN,ESCUELA NACIONAL DE CIENCIAS COMERCIALES,MOISÉS ADRIÁN LÓPEZ PÉREZ,ESTELA DEL CARMEN QUIM ROSALES,DIVERSIFICADO,OFICIAL,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19-09-0902-46,ZACAPA,LA UNION,LICEO PARTICULAR MIXTO JIREH (POR MADUREZ),ASBEL IVÁN SÚCHITE ARROYO,ANA MARÍA CUELLAR GUERRA,DIVERSIFICADO,PRIVADO,URBANA,CERRADA DEFINITIVAMENTE,MONOLINGUE,DOBLE,FIN DE SEMANA,ZACAPA
19-10-0008-46,ZACAPA,HUITE,INSTITUTO NACIONAL DE EDUCACION DIVERSIFICADA,SILDY MARIELA PEREZ FRANCO,--,DIVERSIFICADO,OFICIAL,RURAL,CERRADA DEFINITIVAMENTE,MONOLINGUE,VESPERTINA,DIARIO(REGULAR),ZACAPA
19-10-0013-46,ZACAPA,HUITE,INSTITUTO DIVERSIFICADO,SILDY MARIELA PÉREZ FRANCO,WUENDY JHOJANA SIERRA PAZ,DIVERSIFICADO,OFICIAL,URBANA,ABIERTA,MONOLINGUE,NOCTURNA,DIARIO(REGULAR),ZACAPA
19-10-1009-46,ZACAPA,HUITE,INSTITUTO DIVERSIFICADO POR COOPERATIVA,SILDY MARIELA PÉREZ FRANCO,ROBIDIO PORTILLO SALGUERO,DIVERSIFICADO,COOPERATIVA,URBANA,ABIERTA,MONOLINGUE,VESPERTINA,DIARIO(REGULAR),ZACAPA
19-11-0018-46,ZACAPA,SAN JORGE,INSTITUTO MIXTO DE EDUCACIÓN DIVERSIFICADA POR...,ALBA LUZ MÉNDEZ,VICTOR HUGO GUERRA MONROY,DIVERSIFICADO,COOPERATIVA,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ZACAPA

In [28]:
print("Dimensiones del dataframe: ",df.shape) #tamaño del dataframe

Dimensiones del dataframe:  (8495, 13)

In [26]:
df.info()

<class 'pandas.DataFrame'>
Index: 8495 entries, 16-01-0137-46 to 19-11-0018-46
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DEPARTAMENTO     8495 non-null   str
 1   MUNICIPIO        8495 non-null   str
 2   ESTABLECIMIENTO  8495 non-null   str
 3   SUPERVISOR       8495 non-null   str
 4   DIRECTOR         8495 non-null   str
 5   NIVEL            8495 non-null   str
 6   SECTOR           8495 non-null   str
 7   AREA             8495 non-null   str
 8   STATUS           8495 non-null   str
 9   MODALIDAD        8495 non-null   str
 10  JORNADA          8495 non-null   str
 11  PLAN             8495 non-null   str
 12  DEPARTAMENTAL    8495 non-null   str
dtypes: str(13)
memory usage: 929.1+ KB

Se han dejado 13 variables, todas tipo string

In [27]:
df.describe()

,DEPARTAMENTO,MUNICIPIO,ESTABLECIMIENTO,SUPERVISOR,DIRECTOR,NIVEL,SECTOR,AREA,STATUS,MODALIDAD,JORNADA,PLAN,DEPARTAMENTAL
count,8495,8495,8495,8495,8495,8495,8495,8495,8495,8495,8495,8495,8495
unique,22,329,4353,1180,4843,1,4,3,4,2,6,13,26
top,GUATEMALA,MIXCO,INSTITUTO NACIONAL DE EDUCACION DIVERSIFICADA,ELENA ELIZABETH SUCHITE GARNICA DE QUINTANILLA,---,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,DOBLE,DIARIO(REGULAR),SAN MARCOS
freq,1586,451,344,133,85,8495,6998,6460,5822,8162,2973,5067,659

In [31]:
#Se produce el csv limpio para su posterior análisis
#df.to_csv('DATOS_LIMPIO.csv', sep = ';')