# Obtención de datos
## Grupo 2

##### Importación de librerías.

In [1]:
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select

##### Dirección de los datos.

In [2]:
url = 'https://www.mineduc.gob.gt/BUSCAESTABLECIMIENTO_GE/wbfBuscar.aspx'

##### Captura de datos.

In [3]:
# Listado de departamentos.
departamentos = ['ALTA VERAPAZ', 'BAJA VERAPAZ',
                 'CHIMALTENANGO', 'CHIQUIMULA',
                 'EL PROGRESO', 'ESCUINTLA',
                 'GUATEMALA', 'HUEHUETENANGO',
                 'IZABAL', 'JALAPA',
                 'JUTIAPA', 'PETEN',
                 'QUETZALTENANGO', 'QUICHE',
                 'RETALHULEU', 'SACATEPEQUEZ',
                 'SAN MARCOS', 'SANTA ROSA',
                 'SOLOLA', 'SUCHITEPEQUEZ',
                 'TOTONICAPAN', 'ZACAPA']

In [4]:
departamentos_df = []
for dep in departamentos:

    # Abrir Chrome
    driver = webdriver.Chrome()
    driver.get(url)
    time.sleep(2)

    # Menús desplegables.
    selects = driver.find_elements(By.TAG_NAME, "select")
    Select(selects[0]).select_by_visible_text(dep)
    time.sleep(1)
    selects = driver.find_elements(By.TAG_NAME, "select")
    Select(selects[2]).select_by_visible_text("DIVERSIFICADO")

    # Botón de consulta.
    boton = driver.find_element(By.ID, "_ctl0_ContentPlaceHolder1_IbtnConsultar")
    boton.click()
    time.sleep(3)
    
    # Extraer las tablas de la página
    tablas = pd.read_html(driver.page_source)
    df = tablas[-1]

    departamentos_df.append(df)
    driver.quit()
    time.sleep(3)

C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)
C:\Users\ricro\AppData\Local\Temp\ipykernel_27240\1167934308.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(driver.page_source)

##### Verificando los resultados.

In [5]:
departamentos_df[0].head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,NaN,CODIGO,DISTRITO,DEPARTAMENTO,MUNICIPIO,ESTABLECIMIENTO,DIRECCION,TELEFONO,SUPERVISOR,DIRECTOR,NIVEL,SECTOR,AREA,STATUS,MODALIDAD,JORNADA,PLAN,DEPARTAMENTAL
1,NaN,16-01-0137-46,16-006,ALTA VERAPAZ,COBAN,INSTITUTO MIXTO NOCTURNO FRANCISCO MARROQUIN,6A. AVENIDA 1-15 ZONA 4,NaN,JORGE EDUARDO PAQUE LAZARO,--,DIVERSIFICADO,PRIVADO,URBANA,CERRADA DEFINITIVAMENTE,MONOLINGUE,NOCTURNA,DIARIO(REGULAR),ALTA VERAPAZ
2,NaN,16-01-0138-46,16-01-0926,ALTA VERAPAZ,COBAN,COLEGIO COBAN,KM.2 SALIDA A SAN JUAN CHAMELCO ZONA 8,77945104,JOSE ARTURO CHOC CHEN,GUSTAVO ADOLFO SIERRA POP,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
3,NaN,16-01-0139-46,16-01-0927,ALTA VERAPAZ,COBAN,COLEGIO PARTICULAR MIXTO VERAPAZ,KM 209.5 ENTRADA A LA CIUDAD,58015763,ARMANDO AUDILIO POP CUCUL,GILMA DOLORES GUAY PAZ DE LEAL,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
4,NaN,16-01-0140-46,16-01-0926,ALTA VERAPAZ,COBAN,"COLEGIO ""LA INMACULADA""",7A. AVENIDA 11-109 ZONA 6,78232301,JOSE ARTURO CHOC CHEN,VIRGINIA SOLANO SERRANO,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ

In [6]:
for i in range(0, 21):
    print(departamentos_df[i].iloc[0, 2:3], departamentos_df[i].shape[1])

2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18
2    DISTRITO
Name: 0, dtype: object 18

Todos los df tienen los títulos en la primera fila, por lo cual se hará y se eliminará la fila 0, la cual no contiene información.

##### Formateando los DataFrames.

In [7]:
for i, df in enumerate(departamentos_df):
    df = df.drop(columns=[0])
    df.columns = df.iloc[0]
    df = df.iloc[1:]
    departamentos_df[i] = df

##### Concatenando todos los Data Frame.

In [8]:
df_final = pd.concat(departamentos_df, axis=0, ignore_index=True)

In [9]:
df_final.sample(5)

,CODIGO,DISTRITO,DEPARTAMENTO,MUNICIPIO,ESTABLECIMIENTO,DIRECCION,TELEFONO,SUPERVISOR,DIRECTOR,NIVEL,SECTOR,AREA,STATUS,MODALIDAD,JORNADA,PLAN,DEPARTAMENTAL
5459,22-04-0058-46,22-04-1236,JUTIAPA,AGUA BLANCA,"LICEO ""SAN JUAN PABLO II""",BARRIO EL CENTRO,41024810,YELBELY ROXANA VEGA DONADO,CARLOS OSMIN ORELLANA VICENTE,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,DOBLE,FIN DE SEMANA,JUTIAPA
4852,18-01-2928-46,18-01-1062,IZABAL,PUERTO BARRIOS,COLEGIO PARTICULAR MIXTO 'MIGUEL ANGEL ASTURIAS',11 CALLE 10 Y 11 AV.,79481153,ELENA ELIZABETH SUCHITE GARNICA DE QUINTANILLA,LUBIA JUDITH ORELLANA SALAS,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,DOBLE,FIN DE SEMANA,IZABAL
6032,17-09-4152-46,17-025,PETEN,SAN LUIS,COLEGIO NA LEB,CABECERA MUNICIPAL,NaN,FIDEL OMAR HERNÁNDEZ RAMÍREZ,NaN,DIVERSIFICADO,PRIVADO,URBANA,CERRADA DEFINITIVAMENTE,MONOLINGUE,VESPERTINA,DIARIO(REGULAR),PETÉN
3118,01-10-0301-46,01-10-0096,GUATEMALA,SAN JUAN SACATEPEQUEZ,LICEO CIENTÍFICO SAN JUAN BAUTISTA,2DA. CALLE 2-10 ZONA 3,66302406,MIRNA CELESTINA VICENTE CHAJÓN,PEDRO HERNÁNDEZ CHURUMÍA,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,SIN JORNADA,SEMIPRESENCIAL (FIN DE SEMANA),GUATEMALA OCCIDENTE
7166,11-01-0357-46,11-01-0517,RETALHULEU,RETALHULEU,"COLEGIO PRIVADO MIXTO ""LUIS CARDOZA Y ARAGÓN""","1A. CALLE 8-71, ZONA 1",42227251,ALBA YADIRA MONTEJOS MARTINEZ DE ESPINOZA,ANGEL IGNACIO VASQUEZ GARCIA,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),RETALHULEU

##### Exportando a csv.

In [10]:
df_final.to_csv('DATOS_CRUDOS.csv', index=False)